// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-b1xTepbWpaiNgbOAgz9XjXA3tkqEWs',
    appId: '1:804138084148:web:2526e932f55c7d47802761',
    messagingSenderId: '804138084148',
    projectId: 'flutter-rey-summit-marketing',
    authDomain: 'flutter-rey-summit-marketing.firebaseapp.com',
    storageBucket: 'flutter-rey-summit-marketing.firebasestorage.app',
    measurementId: 'G-XM5MPLKSE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTYLXYDTKUN8R_drHEp-OIjytFbjLj2Y',
    appId: '1:804138084148:android:6ea8fc16887f4214802761',
    messagingSenderId: '804138084148',
    projectId: 'flutter-rey-summit-marketing',
    storageBucket: 'flutter-rey-summit-marketing.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp8_c9nMI4YUcY7Q8bnCk9iWOCD0Lc0Kk',
    appId: '1:804138084148:ios:f165393e83a80df6802761',
    messagingSenderId: '804138084148',
    projectId: 'flutter-rey-summit-marketing',
    storageBucket: 'flutter-rey-summit-marketing.firebasestorage.app',
    iosBundleId: 'com.example.testForApdev',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp8_c9nMI4YUcY7Q8bnCk9iWOCD0Lc0Kk',
    appId: '1:804138084148:ios:f165393e83a80df6802761',
    messagingSenderId: '804138084148',
    projectId: 'flutter-rey-summit-marketing',
    storageBucket: 'flutter-rey-summit-marketing.firebasestorage.app',
    iosBundleId: 'com.example.testForApdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ-b1xTepbWpaiNgbOAgz9XjXA3tkqEWs',
    appId: '1:804138084148:web:ed56c42d6ca8658a802761',
    messagingSenderId: '804138084148',
    projectId: 'flutter-rey-summit-marketing',
    authDomain: 'flutter-rey-summit-marketing.firebaseapp.com',
    storageBucket: 'flutter-rey-summit-marketing.firebasestorage.app',
    measurementId: 'G-EGQQ448J95',
  );
}
